# coding: utf-8

"""
    Argo

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v2.3.0-rc1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest


class TestIoArgoprojWorkflowV1alpha1Outputs(unittest.TestCase):
    """IoArgoprojWorkflowV1alpha1Outputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIoArgoprojWorkflowV1alpha1Outputs(self):
        """Test IoArgoprojWorkflowV1alpha1Outputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.io_argoproj_workflow_v1alpha1_outputs.IoArgoprojWorkflowV1alpha1Outputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
